version: '3.4'

services:
  toxpipe-mcp:
    container_name: toxpipe-mcp
    image: cbtmcp
    ports:
      - "9222:9222"
    restart: unless-stopped
    networks:
      - autonomous

# Traefik network
networks:
  autonomous:
    driver: overlay
    external: true

volumes:
  toxpipe-mcp:
